version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_service
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

  eureka-server:
    build: ./euraka-server
    container_name: eureka_service
    ports:
      - "8761:8761"
    networks:
      - app-network

  apigateway:
    build: ./apigateway
    container_name: apigateway_service
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: apigateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - app-network

  adminservice:
    build: ./adminservice
    container_name: admin_service
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: adminservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/AdminService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network

  clinicadmin:
    build: ./clinicadmin
    container_name: clinicadmin_service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: clinicadmin
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ClinicAdminService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network

  category-services:
    build: ./category-services
    container_name: category_service
    ports:
      - "8800:8800"
    environment:
      SPRING_APPLICATION_NAME: category-services
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/CategoryService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network
  
  doctor-service:
    build: ./doctor-service
    container_name: doctor_service
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: doctor-service
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/DermacareDoctorDB
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network
  
  customerservice:
    build: ./customerservice
    container_name: customer_service
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: customerservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/customerService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network
  
  bookingservice:
    build: ./bookingservice
    container_name: booking_service
    ports:
      - "9900:9900"
    environment:
      SPRING_APPLICATION_NAME: bookingservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/customerbooking
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network
  
  notificationservice:
    build: ./notificationservice
    container_name: notification_service
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_NAME: notificationservice
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/NotificationService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - app-network
  
  # clinicadmin-frontend:
  #   build: ./clinicadmin-frontend
  #   container_name: clinicadmin_frontend
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - HOST=192.168.0.108
  #     - PORT=3000
  #   networks:
  #     - app-network
  #   depends_on:
  #     - apigateway
  #   restart: always



networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
